"""Render matched tenders into a daily email digest and deliver it.

One digest per profile: title, buyer, deadline, value, link, and the classifier's
one-line fit reason (TenderFit.summary) for every "bid" or "maybe" tender that
hasn't already been sent to this profile before (dedup handled by the caller,
runner.py, via the per-profile seen-state file).

Delivery is SMTP, configured entirely from env vars:
    SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, DIGEST_FROM
The recipient comes from the firm profile's `recipient_email`.

--dry-run never touches the network: it writes the rendered HTML to
    out/digest-<profile>-<date>.html
so the digest can be reviewed/tested without sending real mail.
"""

from __future__ import annotations

import argparse
import os
import smtplib
from datetime import date
from email.message import EmailMessage
from pathlib import Path

from profile import FirmProfile, load_profile

OUT_DIR = Path("out")

_HTML_TEMPLATE = """<!doctype html>
<html>
<head><meta charset="utf-8"><title>Tender Radar — {firm_name}</title></head>
<body style="font-family: Arial, Helvetica, sans-serif; color: #1a1a1a; max-width: 640px; margin: 0 auto;">
  <h2 style="margin-bottom: 0;">Tender Radar — {firm_name}</h2>
  <p style="color: #555; margin-top: 4px;">{date} &mdash; {count} new tender(s) worth a look</p>
  {items_html}
  <p style="color: #999; font-size: 12px; margin-top: 32px;">
    Generated by Tender Radar. Verdicts are advisory — always confirm mandatory
    requirements against the full notice before bidding.
  </p>
</body>
</html>
"""

_ITEM_HTML_TEMPLATE = """
  <div style="border: 1px solid #ddd; border-radius: 6px; padding: 14px 16px; margin: 14px 0;">
    <div style="font-size: 11px; font-weight: bold; color: {badge_color}; text-transform: uppercase;">{verdict}</div>
    <h3 style="margin: 4px 0;"><a href="{url}" style="color: #1a1a1a; text-decoration: none;">{title}</a></h3>
    <div style="color: #555; font-size: 14px;">
      <div><strong>Buyer:</strong> {buyer}</div>
      <div><strong>Deadline:</strong> {deadline}</div>
      <div><strong>Value:</strong> {value}</div>
    </div>
    <p style="margin: 8px 0 0; font-size: 14px;">{reason}</p>
    {requirements_html}
    <a href="{url}" style="font-size: 13px;">View notice &rarr;</a>
  </div>
"""

_REQUIREMENTS_HTML_TEMPLATE = """
    <div style="margin: 10px 0 0; padding: 10px 12px; background: #f5f7fa; border-radius: 5px; font-size: 13px; color: #333;">
      <div style="font-weight: bold; color: #444; margin-bottom: 4px;">What they ask for</div>
      {rows}
    </div>
"""

_BADGE_COLOR = {"bid": "#0a7c2f", "maybe": "#a66a00", "skip": "#999999"}


def _requirements_block(t: dict) -> tuple[str, list[str]]:
    """Build the entry-requirements block (P3) from fields the classifier already
    extracted: certs, insurance, contract length, site visit, and the gap list.
    Returns (html, plain_text_lines). Empty when the tender stated nothing useful."""
    rows: list[tuple[str, str]] = []
    certs = t.get("required_certs") or []
    if certs:
        rows.append(("Certifications", ", ".join(certs)))
    if t.get("insurance_required"):
        rows.append(("Insurance", t["insurance_required"]))
    if t.get("contract_length"):
        rows.append(("Contract length", t["contract_length"]))
    if t.get("site_visit_required") is True:
        rows.append(("Site visit", "required before bidding"))
    gaps = t.get("missing_requirements") or []
    if gaps:
        rows.append(("Your gaps to check", "; ".join(gaps)))

    if not rows:
        return "", []

    html_rows = "\n".join(f"<div><strong>{label}:</strong> {value}</div>" for label, value in rows)
    html = _REQUIREMENTS_HTML_TEMPLATE.format(rows=html_rows)
    text_lines = ["  What they ask for:"] + [f"    - {label}: {value}" for label, value in rows]
    return html, text_lines


_EXPIRY_ITEM_TEMPLATE = """
  <div style="border: 1px solid #d8cfe8; border-radius: 6px; padding: 14px 16px; margin: 14px 0; background: #faf8ff;">
    <div style="font-size: 11px; font-weight: bold; color: #5b2d8f; text-transform: uppercase;">re-tender expected</div>
    <h3 style="margin: 4px 0;"><a href="{url}" style="color: #1a1a1a; text-decoration: none;">{title}</a></h3>
    <div style="color: #555; font-size: 14px;">
      <div><strong>Buyer:</strong> {buyer}</div>
      <div><strong>Current holder:</strong> {incumbent}</div>
      <div><strong>Contract ends:</strong> {contract_end}</div>
      <div><strong>Value:</strong> {value}</div>
    </div>
    <p style="margin: 8px 0 0; font-size: 14px;">Re-tenders are typically published 3&ndash;6 months
    before the end date &mdash; worth contacting the buyer early.</p>
    <a href="{url}" style="font-size: 13px;">View award notice &rarr;</a>
  </div>
"""


def _render_expiries_section(expiries: list[dict]) -> str:
    if not expiries:
        return ""
    items = "\n".join(
        _EXPIRY_ITEM_TEMPLATE.format(
            url=e["url"],
            title=e["title"],
            buyer=e["buyer"],
            incumbent=e.get("incumbent") or "not stated",
            contract_end=e["contract_end"],
            value=e.get("value_hint") or "not stated",
        )
        for e in expiries
    )
    return (
        '<h3 style="margin: 28px 0 0; color: #5b2d8f;">Contracts near you expiring soon</h3>\n'
        '<p style="color: #555; margin-top: 4px; font-size: 14px;">No notice published yet &mdash; '
        "these are live contracts whose end date is public. Early contact beats the alert services.</p>\n"
        + items
    )


def render(
    firm: FirmProfile,
    tenders: list[dict],
    run_date: date | None = None,
    expiries: list[dict] | None = None,
) -> tuple[str, str]:
    """tenders: list of TenderFit.model_dump() dicts (already filtered to bid/maybe).
    expiries: optional retender.py records (awards expiring soon, no notice yet).

    Returns (html, plain_text).
    """
    run_date = run_date or date.today()
    expiries = expiries or []

    items_html = "\n".join(
        _ITEM_HTML_TEMPLATE.format(
            verdict=t["bid_recommendation"],
            badge_color=_BADGE_COLOR.get(t["bid_recommendation"], "#999999"),
            url=t["url"],
            title=t["title"],
            buyer=t["buyer"],
            deadline=t.get("deadline") or "not specified",
            value=t.get("estimated_value") or "not specified",
            reason=t["summary"],
            requirements_html=_requirements_block(t)[0],
        )
        for t in tenders
    )
    items_html = (items_html or "<p>No new matching tenders today.</p>") + _render_expiries_section(
        expiries
    )
    html = _HTML_TEMPLATE.format(
        firm_name=firm.name,
        date=run_date.isoformat(),
        count=len(tenders),
        items_html=items_html,
    )

    lines = [
        f"Tender Radar - {firm.name}",
        f"{run_date.isoformat()} - {len(tenders)} new tender(s)",
        "",
    ]
    for t in tenders:
        lines += [
            f"[{t['bid_recommendation'].upper()}] {t['title']}",
            f"  Buyer: {t['buyer']}",
            f"  Deadline: {t.get('deadline') or 'not specified'}",
            f"  Value: {t.get('estimated_value') or 'not specified'}",
            f"  {t['summary']}",
        ]
        lines += _requirements_block(t)[1]
        lines += [f"  {t['url']}", ""]
    if not tenders:
        lines.append("No new matching tenders today.")
    for e in expiries:
        lines += [
            "",
            f"[RE-TENDER EXPECTED] {e['title']}",
            f"  Buyer: {e['buyer']}",
            f"  Current holder: {e.get('incumbent') or 'not stated'}",
            f"  Contract ends: {e['contract_end']}",
            f"  Value: {e.get('value_hint') or 'not stated'}",
            f"  {e['url']}",
        ]
    text = "\n".join(lines)

    return html, text


def _send_smtp(firm: FirmProfile, html: str, text: str, subject: str) -> None:
    host = os.environ.get("SMTP_HOST")
    port = int(os.environ.get("SMTP_PORT", "587"))
    user = os.environ.get("SMTP_USER")
    password = os.environ.get("SMTP_PASS")
    sender = os.environ.get("DIGEST_FROM", user or "")
    if not host or not user or not password:
        raise SystemExit(
            "SMTP_HOST, SMTP_USER and SMTP_PASS must be set in the environment to send "
            "(use --dry-run to render without sending)"
        )

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = firm.recipient_email
    msg.set_content(text)
    msg.add_alternative(html, subtype="html")

    with smtplib.SMTP(host, port) as smtp:
        smtp.starttls()
        smtp.login(user, password)
        smtp.send_message(msg)


def deliver(
    profile_name: str,
    firm: FirmProfile,
    tenders: list[dict],
    dry_run: bool = True,
    run_date: date | None = None,
    expiries: list[dict] | None = None,
) -> Path | None:
    """Render the digest and either write it to out/ (dry-run) or send it via SMTP.

    Returns the path written in dry-run mode, or None when sent (or skipped because
    there was nothing to report).
    """
    expiries = expiries or []
    if not tenders and not expiries:
        return None

    run_date = run_date or date.today()
    html, text = render(firm, tenders, run_date, expiries=expiries)
    n_bits = [f"{len(tenders)} match(es)"] + (
        [f"{len(expiries)} expiring contract(s)"] if expiries else []
    )
    subject = f"Tender Radar — {' + '.join(n_bits)} for {firm.name} ({run_date.isoformat()})"

    if dry_run:
        OUT_DIR.mkdir(exist_ok=True)
        out_path = OUT_DIR / f"digest-{profile_name}-{run_date.isoformat()}.html"
        out_path.write_text(html, encoding="utf-8")
        return out_path

    _send_smtp(firm, html, text, subject)
    return None


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--profile", default="cleaning")
    parser.add_argument(
        "--outputs", default=None, help="defaults to data/tender-outputs-<profile>.jsonl"
    )
    parser.add_argument("--dry-run", action="store_true", default=True)
    parser.add_argument(
        "--send", dest="dry_run", action="store_false", help="actually send via SMTP"
    )
    args = parser.parse_args()

    import json

    firm = load_profile(args.profile)
    outputs_path = (
        Path(args.outputs) if args.outputs else Path(f"data/tender-outputs-{args.profile}.jsonl")
    )
    if not outputs_path.exists():
        raise SystemExit(f"{outputs_path} not found — run runner.py --profile {args.profile} first")

    tenders = [
        json.loads(line)
        for line in outputs_path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    matched = [t for t in tenders if t["bid_recommendation"] in ("bid", "maybe")]

    result = deliver(args.profile, firm, matched, dry_run=args.dry_run)
    if result:
        print(f"  wrote {result}")
    elif not matched:
        print("  no bid/maybe tenders to digest")
    else:
        print(f"  sent digest to {firm.recipient_email}")


if __name__ == "__main__":
    main()
